name: ml
channels:
  - conda-forge
  - defaults
  - auto
dependencies:
  - abseil-cpp
  - absl-py
  - aiohttp
  - anyio
  - appdirs
  - appnope
  - argon2-cffi
  - astroid
  - astunparse
  - async-timeout
  - async_generator
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - bleach
  - blinker
  - blosc
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - certifi
  - cffi
  - cfitsio
  - chardet
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - cryptography
  - cycler
  - cytoolz
  - dask-core
  - dataclasses
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - fasttext
  - freetype
  - fsspec
  - gast
  - giflib
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpc-cpp
  - grpcio
  - h5py
  - hdf5
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - isort
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jxrlib
  - keras
  - keras-preprocessing
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lcms2
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libtiff
  - libwebp-base
  - libzlib
  - libzopfli
  - llvm-openmp
  - locket
  - lz4-c
  - markdown
  - markupsafe
  - matplotlib=3.4.3
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mistune
  - multidict
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - numpy
  - oauthlib
  - olefile
  - openjpeg
  - openssl
  - opt_einsum
  - packaging
  - pandas=1.3.4
  - pandoc
  - pandocfilters
  - parso
  - partd
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pooch
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pyasn1
  - pyasn1-modules
  - pybind11
  - pybind11-global
  - pycparser
  - pygments
  - pyjwt
  - pylint
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python=3.9.1
  - python-dateutil
  - python-flatbuffers
  - python_abi
  - pytz
  - pyu2f
  - pywavelets
  - pyyaml
  - pyzmq
  - re2
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scikit-image=0.18.3
  - scikit-learn=1.0.1
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - six
  - snappy
  - sniffio
  - sqlite
  - statsmodels
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow=2.6.0
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - terminado
  - testpath
  - threadpoolctl
  - tifffile
  - tk
  - toml
  - toolz
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - wrapt
  - xz
  - yaml
  - yarl
  - zeromq
  - zfp
  - zipp
  - zlib
  - zstd
